spring:
  application:
    name: filter-service
  data:
    mongodb:
      uri: mongodb://kalayciburak:123456@127.0.0.1:27017/filterdb?authSource=admin
  kafka:
    consumer:
      auto-offset-reset: earliest
      bootstrap-servers: http://127.0.0.1:9092
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: "com.kalayciburak.*"
server:
  servlet:
    context-path: /api/filter-service
  port: 8081

# Graylog configuration
graylog:
  host: 127.0.0.1
  port: 12201